/* Generated By:JavaCC: Do not edit this line. RdfPatchParserImplConstants.java */
package org.apache.marmotta.platform.ldp.patch.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RdfPatchParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRLIT = 7;
  /** RegularExpression Id. */
  int STRLONGLIT = 8;
  /** RegularExpression Id. */
  int OP = 11;
  /** RegularExpression Id. */
  int REPEAT = 12;
  /** RegularExpression Id. */
  int UNDEFINED = 13;
  /** RegularExpression Id. */
  int PREFIX = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int IDENT = 17;
  /** RegularExpression Id. */
  int URI = 18;
  /** RegularExpression Id. */
  int BNODE = 19;
  /** RegularExpression Id. */
  int QNAME = 20;
  /** RegularExpression Id. */
  int LANG = 21;
  /** RegularExpression Id. */
  int TYPE = 22;
  /** RegularExpression Id. */
  int COMMENT = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinString = 1;
  /** Lexical state. */
  int WithinLongString = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\\\"\\\"\"",
    "\"\\\"\"",
    "<STRLIT>",
    "<STRLONGLIT>",
    "<token of kind 9>",
    "<token of kind 10>",
    "<OP>",
    "\"R\"",
    "\"U\"",
    "\"@prefix\"",
    "\".\"",
    "\":\"",
    "<IDENT>",
    "<URI>",
    "<BNODE>",
    "<QNAME>",
    "\"@\"",
    "\"^^\"",
    "<COMMENT>",
  };

}
